FROM nvcr.io/partners/gridai/pytorch-lightning:v1.4.0
RUN pip install fair-esm && \
    pip install biopython && \
    pip install scikit-learn && \
    pip install bertviz && \
    pip install skl2onnx && \
    pip install onnxruntime && \
    pip install spacy && \
    pip install plotly && \
    pip install wandb
WORKDIR /
RUN git clone https://github.com/PeptoneLtd/ADOPT.git
WORKDIR /ADOPT
RUN git submodule update --init --recursive && \
    python setup.py install